services:
  db-test:
    image: postgres:18

    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: mouse_analytics_test

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d mouse_analytics_test"]
      interval: 2s
      timeout: 3s
      retries: 10




  kafka-init-test:
    image: apache/kafka:4.3.1

    depends_on:
      kafka-test:
        condition: service_healthy

    command:
      - /bin/sh
      - -c
      - |
        echo "Creating test Kafka topic..."

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka-test:29093 \
          --create \
          --if-not-exists \
          --topic mouse-events-test \
          --partitions 1 \
          --replication-factor 1

        echo "Test topic ready:"
        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka-test:29093 \
          --list




  kafka-test:
    image: apache/kafka:4.3.1

    ports:
      - "9093:9093"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-test:9094

      KAFKA_LISTENERS: EXTERNAL://:9093,INTERNAL://:29093,CONTROLLER://:9094

      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9093,INTERNAL://kafka-test:29093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9093 || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s