name: CI

on:
  push:
  pull_request:

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest tests/test_unit -v


  integration-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          ./scripts/run_integration_tests.sh


  build-and-push:

    needs:
      - unit-tests
      - integration-tests

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push backend image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: backend/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/mouse-analytics:backend-${{ github.sha }}

      - name: Build and push consumers image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: consumers/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/mouse-analytics:consumers-${{ github.sha }}

  deploy:
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            cd ~/mouse_analytics

            IMAGE_TAG=${{ github.sha }} docker compose -f docker-compose.prod.yml pull

            IMAGE_TAG=${{ github.sha }} docker compose -f docker-compose.prod.yml up -d